
name: Manual workflow

on:
  workflow_dispatch:
  push:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch command
      run: git fetch origin 157e00ce92a383048ce48cc76e10731064129b86
    - name: Checkout command
      run: git checkout 157e00ce92a383048ce48cc76e10731064129b86
    - name: Make script executable
      run: chmod +x unit_tests_should_not_fail.sh
    - name: Change the failed tests
      run: ./unit_tests_should_not_fail.sh
    - name: Build
      run: ./gradlew build
    - name: Run server
      run: ./gradlew sonar-server:run
    
  
      
